processor:
  ignoreTypes:
    - "(Compactor|Gateway|Ingester|Query|QueryFrontend|Router|Ruler|Service|Storage|Store|Tenant)List$"
  ignoreFields:
    - "TypeMeta$"

render:
  kubernetesVersion: 1.26
  knownTypes:
    - name: SecretObjectReference
      package: sigs.k8s.io/gateway-api/apis/v1beta1
      link: https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.SecretObjectReference