- name: thanos-compact
  rules:
  - alert: ThanosCompactMultipleRunning
    annotations:
      description: No more than one Thanos Compact instance should be running at once. There are {{$value}} instances running.
      runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompactmultiplerunning
      summary: Thanos Compact has multiple instances running.
    expr: up{pod!~".*-0", job=~".*compactor.*"} > 0
    for: 5m
    labels:
      severity: warning
  - alert: ThanosCompactHalted
    annotations:
      description: Thanos Compact {{$labels.job}} has failed to run and now is halted.
      runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompacthalted
      summary: Thanos Compact has failed to run and is now halted.
    expr: thanos_compact_halted{job=~".*compactor.*"} == 1
    for: 5m
    labels:
      severity: warning
  - alert: ThanosCompactHighCompactionFailures
    annotations:
      description: Thanos Compact {{$labels.job}} is failing to execute {{$value | humanize}}% of compactions.
      runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompacthighcompactionfailures
      summary: Thanos Compact is failing to execute compactions.
    expr: |
      (
        sum by (job) (rate(thanos_compact_group_compactions_failures_total{job=~".*compactor.*"}[5m]))
      /
        sum by (job) (rate(thanos_compact_group_compactions_total{job=~".*compactor.*"}[5m]))
      * 100 > 5
      )
    for: 15m
    labels:
      severity: warning
  - alert: ThanosCompactBucketHighOperationFailures
    annotations:
      description: Thanos Compact {{$labels.job}} Bucket is failing to execute {{$value | humanize}}% of operations.
      runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompactbuckethighoperationfailures
      summary: Thanos Compact Bucket is having a high number of operation failures.
    expr: |
      (
        sum by (job) (rate(thanos_objstore_bucket_operation_failures_total{job=~".*compactor.*"}[5m]))
      /
        sum by (job) (rate(thanos_objstore_bucket_operations_total{job=~".*compactor.*"}[5m]))
      * 100 > 5
      )
    for: 15m
    labels:
      severity: warning
  - alert: ThanosCompactHasNotRun
    annotations:
      description: Thanos Compact {{$labels.job}} has not uploaded anything for 24 hours.
      runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompacthasnotrun
      summary: Thanos Compact has not uploaded anything for last 24 hours.
    expr: (time() - max by (job) (max_over_time(thanos_objstore_bucket_last_successful_upload_time{job=~".*compactor.*"}[24h]))) / 60 / 60 > 24
    labels:
      severity: warning
