- name: thanos-receive
  rules:
  - alert: ThanosReceiveHttpRequestErrorRateHigh
    annotations:
      description: Thanos Receive {{$labels.job}} is failing to handle {{$value | humanize}}% of requests.
      runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceivehttprequesterrorratehigh
      summary: Thanos Receive is failing to handle requests.
    expr: |
      (
        sum by (job) (rate(http_requests_total{code=~"5..", job=~".*ingester.*", handler="receive"}[5m]))
      /
        sum by (job) (rate(http_requests_total{job=~".*ingester.*", handler="receive"}[5m]))
      ) * 100 > 5
    for: 5m
    labels:
      severity: critical
  - alert: ThanosReceiveHttpRequestLatencyHigh
    annotations:
      description: Thanos Receive {{$labels.job}} has a 99th percentile latency of {{ $value }} seconds for requests.
      runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceivehttprequestlatencyhigh
      summary: Thanos Receive has high HTTP requests latency.
    expr: |
      (
        histogram_quantile(0.99, sum by (job, le) (rate(http_request_duration_seconds_bucket{job=~".*ingester.*", handler="receive"}[5m]))) > 10
      and
        sum by (job) (rate(http_request_duration_seconds_count{job=~".*ingester.*", handler="receive"}[5m])) > 0
      )
    for: 10m
    labels:
      severity: critical
  - alert: ThanosReceiveHighReplicationFailures
    annotations:
      description: Thanos Receive {{$labels.job}} is failing to replicate {{$value | humanize}}% of requests.
      runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceivehighreplicationfailures
      summary: Thanos Receive is having high number of replication failures.
    expr: |
      thanos_receive_replication_factor > 1
        and
      (
        (
          sum by (job) (rate(thanos_receive_replications_total{result="error", job=~".*ingester.*"}[5m]))
        /
          sum by (job) (rate(thanos_receive_replications_total{job=~".*ingester.*"}[5m]))
        )
        >
        (
          max by (job) (floor((thanos_receive_replication_factor{job=~".*ingester.*"}+1) / 2))
        /
          max by (job) (thanos_receive_hashring_nodes{job=~".*ingester.*"})
        )
      ) * 100
    for: 5m
    labels:
      severity: warning
  - alert: ThanosReceiveHighForwardRequestFailures
    annotations:
      description: Thanos Receive {{$labels.job}} is failing to forward {{$value | humanize}}% of requests.
      runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceivehighforwardrequestfailures
      summary: Thanos Receive is failing to forward requests.
    expr: |
      (
        sum by (job) (rate(thanos_receive_forward_requests_total{result="error", job=~".*ingester.*"}[5m]))
      /
        sum by (job) (rate(thanos_receive_forward_requests_total{job=~".*ingester.*"}[5m]))
      ) * 100 > 20
    for: 5m
    labels:
      severity: info
  - alert: ThanosReceiveHighHashringFileRefreshFailures
    annotations:
      description: Thanos Receive {{$labels.job}} is failing to refresh hashring file, {{$value | humanize}} of attempts failed.
      runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceivehighhashringfilerefreshfailures
      summary: Thanos Receive is failing to refresh hasring file.
    expr: |
      (
        sum by (job) (rate(thanos_receive_hashrings_file_errors_total{job=~".*ingester.*"}[5m]))
      /
        sum by (job) (rate(thanos_receive_hashrings_file_refreshes_total{job=~".*ingester.*"}[5m]))
      > 0
      )
    for: 15m
    labels:
      severity: warning
  - alert: ThanosReceiveConfigReloadFailure
    annotations:
      description: Thanos Receive {{$labels.job}} has not been able to reload hashring configurations.
      runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceiveconfigreloadfailure
      summary: Thanos Receive has not been able to reload configuration.
    expr: avg by (job) (thanos_receive_config_last_reload_successful{job=~".*ingester.*"}) != 1
    for: 5m
    labels:
      severity: warning
  - alert: ThanosReceiveNoUpload
    annotations:
      description: Thanos Receive {{$labels.instance}} has not uploaded latest data to object storage.
      runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceivenoupload
      summary: Thanos Receive has not uploaded latest data to object storage.
    expr: |
      (up{job=~".*ingester.*"} - 1)
      + on (job, instance) # filters to only alert on current instance last 3h
      (sum by (job, instance) (increase(thanos_shipper_uploads_total{job=~".*ingester.*"}[3h])) == 0)
    for: 3h
    labels:
      severity: critical
