
---
apiVersion: monitoring.whizard.io/v1alpha1
kind: Service
metadata:
  name: whizard
  namespace: kubesphere-monitoring-system
spec:
  tenantHeader: "WHIZARD-TENANT"
  defaultTenantId: "default-tenant"
  tenantLabelName: "tenant_id"
  compactorTemplateSpec:
    securityContext:
      fsGroup: 0
    dataVolume:
      emptyDir: {}
    flags:
      - --block-files-concurrency=20
      - --compact.blocks-fetch-concurrency=5
      - --web.disable
      - --compact.enable-vertical-compaction
    image: thanosio/thanos:v0.33.0
  gatewayTemplateSpec: {}
  ingesterTemplateSpec: 
    securityContext:
      fsGroup: 0
    dataVolume:
      emptyDir: {}
    flags:
      - --tsdb.out-of-order.time-window=10m
  queryTemplateSpec:
    image: thanosio/thanos:v0.33.0
    flags: 
      - --query.max-concurrent=200
  queryFrontendTemplateSpec:
    image: thanosio/thanos:v0.33.0
  routerTemplateSpec:
    image: thanosio/thanos:v0.33.0
  rulerTemplateSpec:
    rulerWriteProxy:
      image: frezes/cortex-tenant:v1.12.5
    securityContext:
      fsGroup: 0
    dataVolume:
      emptyDir: {}
    ruleSelectors:
      - matchLabels:
          role: alert-rules
    flags:
      - |
        --alert.relabel-config=
          - source_labels: ['job','namespace']
            separator: ;
            regex: '(node-exporter);.*'
            target_label: 'namespace'
            replacement: '$2'
          - source_labels: ['job','pod']
            separator: ;
            regex: '(node-exporter);.*'
            target_label: 'pod'
            replacement: '$2'
    image: thanosio/thanos:v0.33.0
  storeTemplateSpec:
    securityContext:
      fsGroup: 0
    dataVolume:
      emptyDir: {}
    image: thanosio/thanos:v0.33.0
    flags:
      - --web.disable
      - --no-cache-index-header  
---
apiVersion: monitoring.whizard.io/v1alpha1
kind: Gateway
metadata:
  name: whizard
  namespace: kubesphere-monitoring-system
  labels:
    monitoring.whizard.io/service: kubesphere-monitoring-system.whizard
spec: {}

---
apiVersion: monitoring.whizard.io/v1alpha1
kind: Query
metadata:
  name: whizard
  namespace: kubesphere-monitoring-system
  labels:
    monitoring.whizard.io/service: kubesphere-monitoring-system.whizard
spec:
  replicaLabelNames:
    - prometheus_replica
    - receive_replica
    - ruler_replica

---
apiVersion: monitoring.whizard.io/v1alpha1
kind: QueryFrontend
metadata:
  name: whizard
  namespace: kubesphere-monitoring-system
  labels:
    monitoring.whizard.io/service: kubesphere-monitoring-system.whizard
spec: {}


---
apiVersion: monitoring.whizard.io/v1alpha1
kind: Router
metadata:
  name: whizard
  namespace: kubesphere-monitoring-system
  labels:
    monitoring.whizard.io/service: kubesphere-monitoring-system.whizard
spec: {}



---
### global alert ruler
apiVersion: monitoring.whizard.io/v1alpha1
kind: Ruler
metadata:
  labels:
    monitoring.whizard.io/service: kubesphere-monitoring-system.whizard
  name: whizard
  namespace: kubesphere-monitoring-system
spec:
  alertmanagersUrl:
  - dnssrv+http://alertmanager-operated.kubesphere-monitoring-system.svc:9093
  evaluationInterval: 1m
  logFormat: logfmt
  logLevel: info
  replicas: 1
  ruleSelectors:
  - matchExpressions:
    - key: alerting.kubesphere.io/rule_level
      operator: In
      values:
      - global
  shards: 1

---
apiVersion: monitoring.whizard.io/v1alpha1
kind: Tenant
metadata:
  labels:
    monitoring.whizard.io/service: kubesphere-monitoring-system.whizard
    monitoring.whizard.io/storage: default
  name: test
spec: 
  tenant: test