{{- if .Values.queryFrontend.enabled -}}
apiVersion: monitoring.whizard.io/v1alpha1
kind: QueryFrontend
metadata:
  name: {{ include "whizard.queryFrontend.crname" . }}
  namespace: {{ include "whizard.namespace" . }}
  labels:
    {{- if .Values.queryFrontend.serviceReference }}
    "monitoring.whizard.io/service": "{{ .Values.queryFrontend.serviceReference.namespace }}.{{ .Values.queryFrontend.serviceReference.name }}"
    {{- else if .Values.service.enabled }}
    "monitoring.whizard.io/service": "{{ include "whizard.namespace" . }}.{{ include "whizard.service.crname" . }}"
    {{- end }}
    {{- include "whizard.labels" . | nindent 4 }}
spec:
  {{ if .Values.queryFrontend.genSignedCert }}
  httpServerTLSConfig:
    certSecret:
      name: {{ include "whizard.queryFrontend.crname" . }}-query-frontend-tls-assets
      key: tls.crt
    keySecret:
      name: {{ include "whizard.queryFrontend.crname" . }}-query-frontend-tls-assets
      key: tls.key
  {{- else }}
  {{- with .Values.queryFrontend.httpServerTLSConfig }}
  httpServerTLSConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- with .Values.queryFrontend.additionalConfig }}
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- with .Values.queryFrontend.additionalConfigString }}
  {{- tpl . $ | nindent 2 }}
{{- end }}
{{- end }}
