{{- if and .Values.controllerManager.enabled .Values.controllerManager.config.create }}
{{- $config := .Values.controllerManager.config }}
{{- $whizardImage := printf "%s:%s" .Values.global.whizard.image.repository .Values.global.whizard.image.tag }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "whizard.fullname" . }}-config
  namespace: {{ include "whizard.namespace" . }}
  labels:
    {{- include "whizard.labels" . | nindent 4 }}
data:   
  whizard.yaml: |
    monitoring: 

      {{- $storage := $config.storage }}
      storage:
        {{- if $storage.blockManager }}
        blockManager: 
          enable: {{ $storage.blockManager.enable }}
          {{- if $storage.image }}
          image: {{ $storage.image.repository }}:{{ $storage.image.tag }}
          {{- else }}
          image: {{ $whizardImage }}
          {{- end }}
          {{- if $storage.blockManager.serviceAccountName }}
          serviceAccountName: {{ $storage.blockManager.serviceAccountName }}
          {{- else }}
          serviceAccountName: {{ include "whizard.manager.serviceAccountName" . }}
          {{- end }}
          {{- if .Values.global.imagePullSecrets }}
          imagePullSecrets:
          {{- include "whizard.imagePullSecrets" . | trim | nindent  12}}
          {{- end }}
          gc:
            image: "{{ $storage.blockManager.gc.image.repository }}:{{ $storage.blockManager.gc.image.tag | default .Chart.AppVersion }}"
        {{- end }}

      {{- $gateway := $config.gateway }}
      gateway: 
        image: {{ $gateway.image.repository }}:{{ $gateway.image.tag | default .Chart.AppVersion }}
        replicas: {{ $gateway.replicas }}
        {{- if .Values.global.imagePullSecrets }}
        imagePullSecrets:
        {{- include "whizard.imagePullSecrets" . | trim | nindent  10 }}
        {{- end }}

        {{- with $gateway.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
  
        {{- with $gateway.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}       

        logLevel: {{ .Values.global.whizard.log.level }}
        logFormat: {{ .Values.global.whizard.log.format }}

      {{- $router := $config.router }}
      router: 
        {{- if $router.image }}
        image: {{ $router.image.repository }}:{{ $router.image.tag }}
        {{- else }}
        image: {{ $whizardImage }}
        {{- end }}
        {{- if .Values.global.imagePullSecrets }}
        imagePullSecrets:
        {{- include "whizard.imagePullSecrets" . | trim | nindent  10}}
        {{- end }}

        replicas: {{ $router.replicas }}
        {{- with $router.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }} 
        {{- with $router.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        envoy: 
          image: {{ $config.query.envoy.image.repository }}:{{ $config.query.envoy.image.tag }}
        
        logLevel: {{ .Values.global.whizard.log.level }}
        logFormat: {{ .Values.global.whizard.log.format }}
        replicationFactor: {{ $router.replicationFactor }}

        {{- with $router.additionalFlags }}
        flags:
          {{- toYaml . | nindent 10 }}
        {{- end }}

      {{- $queryFrontend := $config.queryFrontend }}
      queryFrontend: 
        {{- if $queryFrontend.image }}
        image: {{ $queryFrontend.image.repository }}:{{ $queryFrontend.image.tag }}
        {{- else }}
        image: {{ $whizardImage }}
        {{- end }}
        {{- if .Values.global.imagePullSecrets }}
        imagePullSecrets:
        {{- include "whizard.imagePullSecrets" . | trim | nindent  10}}
        {{- end }}

        replicas: {{ $queryFrontend.replicas }}
        {{- with $queryFrontend.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}  
        {{- with $queryFrontend.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        envoy: 
          image: {{ $config.query.envoy.image.repository }}:{{ $config.query.envoy.image.tag }}

        logLevel: {{ .Values.global.whizard.log.level }}
        logFormat: {{ .Values.global.whizard.log.format }}
        {{- with $queryFrontend.cacheConfig }}
        cacheConfig:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with $queryFrontend.additionalFlags }}
        flags:
          {{- toYaml . | nindent 10 }}
        {{- end }}

      {{- $query := $config.query }}
      query: 
        {{- if $query.image }}
        image: {{ $query.image.repository }}:{{ $query.image.tag }}
        {{- else }}
        image: {{ $whizardImage }}
        {{- end }}
        {{- if .Values.global.imagePullSecrets }}
        imagePullSecrets:
        {{- include "whizard.imagePullSecrets" . | trim | nindent  10}}
        {{- end }}

        replicas: {{ $query.replicas }}
        {{- with $query.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}  
        {{- with $query.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}        

        logLevel: {{ .Values.global.whizard.log.level }}
        logFormat: {{ .Values.global.whizard.log.format }}

        envoy: 
          image: {{ $query.envoy.image.repository }}:{{ $query.envoy.image.tag }}

        {{- with $query.additionalFlags }}
        flags:
          {{- toYaml . | nindent 10 }}
        {{- end }}

      {{- $ingester := $config.ingester }}
      ingester: 
        {{- if $ingester.image }}
        image: {{ $ingester.image.repository }}:{{ $ingester.image.tag }}
        {{- else }}
        image: {{ $whizardImage }}
        {{- end }}
        {{- if .Values.global.imagePullSecrets }}
        imagePullSecrets:
        {{- include "whizard.imagePullSecrets" . | trim | nindent  10}}
        {{- end }}

        replicas: {{ $ingester.replicas }}
        {{- with $ingester.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}  
        {{- with $ingester.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        logLevel: {{ .Values.global.whizard.log.level }}
        logFormat: {{ .Values.global.whizard.log.format }}
        localTsdbRetention: {{ $ingester.localTsdbRetention }}

        {{- with $ingester.dataVolume }}
        dataVolume:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        disableTSDBCleanup: {{ $ingester.disableTSDBCleanup }}
        tsdbCleanupImage: {{ $ingester.tsdbCleanupImage.repository }}:{{ $ingester.tsdbCleanupImage.tag }}

        {{- with $ingester.additionalFlags }}
        flags:
          {{- toYaml . | nindent 10 }}
        {{- end }}

      {{- $store := $config.store }}
      store: 
        {{- if $store.image }}
        image: {{ $store.image.repository }}:{{ $store.image.tag }}
        {{- else }}
        image: {{ $whizardImage }}
        {{- end }}
        {{- if .Values.global.imagePullSecrets }}
        imagePullSecrets:
        {{- include "whizard.imagePullSecrets" . | trim | nindent  10}}
        {{- end }}

        {{- with $store.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }} 
        {{- with $store.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        logLevel: {{ .Values.global.whizard.log.level }}
        logFormat: {{ .Values.global.whizard.log.format }}
        {{- with $store.indexCacheConfig }}
        indexCacheConfig:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with $store.timeRanges }}
        timeRanges:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with $store.additionalFlags }}
        flags:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with $store.dataVolume }}
        dataVolume:
          {{- toYaml . | nindent 10 }}
        {{- end }}

      {{- $compactor := $config.compactor }}
      compactor: 
        {{- if $compactor.image }}
        image: {{ $compactor.image.repository }}:{{ $compactor.image.tag }}
        {{- else }}
        image: {{ $whizardImage }}
        {{- end }}
        {{- if .Values.global.imagePullSecrets }}
        imagePullSecrets:
        {{- include "whizard.imagePullSecrets" . | trim | nindent  10}}
        {{- end }}

        logLevel: {{ .Values.global.whizard.log.level }}
        logFormat: {{ .Values.global.whizard.log.format }}

        {{- with $compactor.retention }}
        retention:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with $compactor.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }} 
        {{- with $compactor.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}        

        {{- with $compactor.additionalFlags }}
        flags:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with $compactor.dataVolume }}
        dataVolume:
          {{- toYaml . | nindent 10 }}
        {{- end }}

      {{- $ruler := $config.ruler }}
      ruler: 
        {{- if $ruler.image }}
        image: {{ $ruler.image.repository }}:{{ $ruler.image.tag }}
        {{- else }}
        image: {{ $whizardImage }}
        {{- end }}
        {{- if .Values.global.imagePullSecrets }}
        imagePullSecrets:
        {{- include "whizard.imagePullSecrets" . | trim | nindent  10}}
        {{- end }}

        shards: {{ $ruler.shards }}
        replicas: {{ $ruler.replicas }}
        {{- with $ruler.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }} 
        {{- with $ruler.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        logLevel: {{ .Values.global.whizard.log.level }}
        logFormat: {{ .Values.global.whizard.log.format }}
        evaluationInterval: {{ $ruler.evaluationInterval }}
        {{- with $ruler.ruleSelectors }}
        ruleSelectors:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $ruler.ruleNamespaceSelector }}
        ruleNamespaceSelector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $ruler.alertmanagersUrl }}
        alertmanagersUrl:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        prometheusConfigReloader:
          image: {{ $ruler.prometheusConfigReloader.image.repository }}:{{ $ruler.prometheusConfigReloader.image.tag }}
        rulerQueryProxy: 
          image: {{ $gateway.image.repository }}:{{ $gateway.image.tag | default .Chart.AppVersion }}
        rulerWriteProxy: 
          image: {{ $ruler.writeProxy.image.repository }}:{{ $ruler.writeProxy.image.tag }}

        envoy: 
          image: {{ $config.query.envoy.image.repository }}:{{ $config.query.envoy.image.tag }}

        {{- with $ruler.additionalFlags }}
        flags:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{ end }}